// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  accordion: dynamic(() => import("./Accordion")),
  carousel: dynamic(() => import("./Carousel")),
  rich_text: dynamic(() => import("./RichText")),
  table: dynamic(() => import("./Table")),
};
